CREATE TABLE IF NOT EXISTS b_custom_chat_category (
    ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SORT INT NOT NULL DEFAULT 500,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX ix_chat_category_user (USER_ID)
);

CREATE TABLE IF NOT EXISTS b_custom_chat_category_chat (
    ID INT NOT NULL AUTO_INCREMENT,
    CATEGORY_ID INT NOT NULL,
    DIALOG_ID VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE INDEX ux_category_dialog (CATEGORY_ID, DIALOG_ID),
    INDEX ix_category_chat_category (CATEGORY_ID),
    CONSTRAINT fk_custom_chat_category FOREIGN KEY (CATEGORY_ID) REFERENCES b_custom_chat_category(ID) ON DELETE CASCADE
);
